#!/bin/bash
# LLM 智能建图 - 无障碍物版本（纯建图模式）

echo "🗺️  LLM 智能建图 - 无障碍物版本"
echo "================================"
echo ""
echo "此模式用于构建干净的地图，不包含桶等障碍物"
echo ""
echo "📋 启动步骤："
echo ""
echo "终端 1 - 仿真环境（无桶）："
echo "----------------------------------------"
echo "ros2 launch assessment assessment.launch.py \\"
echo "  num_robots:=1 \\"
echo "  use_nav2:=false \\"
echo "  headless:=false \\"
echo "  random_seed:=42 \\"
echo "  barrels:=false"
echo ""
echo "终端 2 - Cartographer SLAM："
echo "----------------------------------------"
echo "ros2 launch assessment cartographer.launch.py \\"
echo "  ns:=robot1 \\"
echo "  use_sim_time:=true \\"
echo "  use_rviz:=true"
echo ""
echo "终端 3 - LLM 建图控制："
echo "----------------------------------------"
echo "cd /workspaces/AURO2025 && source install/setup.bash"
echo "export OPENAI_API_KEY=\"你的API密钥\""
echo "ros2 run solution llm_mapper --ros-args --remap __ns:=/robot1"
echo ""
echo "终端 4 - 保存地图（建图完成后）："
echo "----------------------------------------"
echo "cd /workspaces/AURO2025 && source install/setup.bash"
echo "ros2 run nav2_map_server map_saver_cli -f solution/config/clean_map \\"
echo "  --ros-args -r map:=/robot1/map"
echo ""
echo "或者使用脚本保存 Cartographer 状态："
echo "bash 保存Cartographer状态.sh robot1 clean_map"
echo ""
echo "💡 提示："
echo "  - barrels:=false 会禁用桶的生成"
echo "  - 建图完成后的地图可用于导航阶段"
echo "  - 导航时再启用 barrels:=true 来加载桶"
echo ""
