#!/bin/bash
# AURO2025 建图命令速查
# 使用方法：在 4 个不同的终端中分别执行对应的命令

echo "================================================================================"
echo "AURO2025 建图命令速查"
echo "================================================================================"
echo ""
echo "请在 4 个不同的终端中按顺序执行以下命令："
echo ""
echo "【终端 1 - 启动仿真环境】"
echo "--------------------------------------------------------------------------------"
echo "cd /workspaces/AURO2025"
echo "source install/setup.bash"
echo "ros2 launch assessment assessment.launch.py \\"
echo "  num_robots:=1 \\"
echo "  use_nav2:=false \\"
echo "  use_rviz:=false \\"
echo "  headless:=false \\"
echo "  random_seed:=42"
echo ""
echo "【终端 2 - 启动 Cartographer SLAM + RViz】"
echo "--------------------------------------------------------------------------------"
echo "cd /workspaces/AURO2025"
echo "source install/setup.bash"
echo "ros2 launch assessment cartographer.launch.py \\"
echo "  ns:=robot1 \\"
echo "  use_sim_time:=true \\"
echo "  use_rviz:=true"
echo ""
echo "【终端 3 - 手动遥控机器人】"
echo "--------------------------------------------------------------------------------"
echo "cd /workspaces/AURO2025"
echo "source install/setup.bash"
echo "ros2 run turtlebot3_teleop teleop_keyboard \\"
echo "  --ros-args --remap cmd_vel:=/robot1/cmd_vel"
echo ""
echo "操作键位："
echo "  w=前进  x=后退  a=左转  d=右转  s=停止  空格=急停"
echo ""
echo "【终端 4 - 保存地图】（完成建图后执行）"
echo "--------------------------------------------------------------------------------"
echo "cd /workspaces/AURO2025"
echo "source install/setup.bash"
echo "mkdir -p solution/config"
echo "ros2 run nav2_map_server map_saver_cli -f solution/config/map2 \\"
echo "  --ros-args -r map:=/robot1/map"
echo ""
echo "【验证地图已保存】"
echo "--------------------------------------------------------------------------------"
echo "ls -lh solution/config/map2.*"
echo ""
echo "【测试地图 + Nav2】"
echo "--------------------------------------------------------------------------------"
echo "ros2 launch solution solution_launch.py \\"
echo "  num_robots:=1 \\"
echo "  random_seed:=42 \\"
echo "  use_nav2:=true \\"
echo "  headless:=false"
echo ""
echo "================================================================================"
echo "详细说明请查看：正确的建图步骤.md"
echo "================================================================================"
